#:schema node_modules/wrangler/config-schema.json
name = "smail"
compatibility_date = "2024-09-25"
main = "app/worker.ts"
assets = { directory = "./build/client" }

[observability]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "51dc159a9397451ead0ac4650c3807a4"

[[d1_databases]]
binding = "DB"
database_name = "smail"
database_id = "e5d06e78-07c0-4515-a3c9-c509507fbbc7"
preview_database_id = "e5d06e78-07c0-4515-a3c9-c509507fbbc7"
migrations_dir = "app/drizzle"
